name: Node JS CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs: 

  test: 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup node
      uses: actions/setup-node@v3
      with: 
        node-version: lts
    
    - name: Install node_modules
      run: npm ci

    - name: Run Tests
      run: npm run test
    
  lint:
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Setup node
      uses: actions/setup-node@v3
      with: 
        node-version: lts
    
    - name: Install node_modules
      run: npm ci

    - name: Lint
      run: npm run eslint